name: untitled
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  url_launcher: ^6.0.10
  image_picker: ^0.8.4+3
  permission_handler: ^10.2.0
  dio: ^4.0.1
  retrofit: ^3.0.0
  json_annotation: ^4.7.0
  analyzer: ^5.13.0
  jwt_decode: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  retrofit_generator: ^4.2.0
  json_serializable: ^6.5.0




flutter:

  uses-material-design: true
  assets:
    - assets/images/splash_bg.jpg
    - assets/images/mosfurex.png
    - assets/images/sofa.jpeg
    - assets/images/sofatop.jpeg
    - assets/images/ottoman.jpg
    - assets/images/divan.jpg
    - assets/images/headboard_vertical_lines.jpg
    - assets/images/headboard_cubes.jpeg
    - assets/images/headboard_minimalist.jpeg
    - assets/images/headboard_chesterfield.jpeg
    - assets/images/headboard_circle_winged.jpeg
    - assets/images/headboard_cubed_small.jpeg
    - assets/images/headboard_horizontal_lined.jpeg
    - assets/images/headboard_modern_minimalist.jpeg
    - assets/images/headboard_default.jpg
    - assets/images/paypal.png
    - assets/images/razorpay.png
    - assets/images/stripe.png
    - assets/images/mastercard.png
    - assets/images/visa.png
    - assets/images/plush.jpeg
    - assets/images/wool.jpeg
    - assets/images/linen.jpeg
    - assets/images/velvet.jpeg
    - assets/images/chenielle.jpeg
    - assets/images/naples.jpeg
    - assets/images/chair.jpeg
    - assets/images/bed1.jpeg



